<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>patient_vaccination_registry.Aplication</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\patient-vaccination-registry.Infrastructure\patient-vaccination-registry.Infrastructure.csproj" />
  </ItemGroup>

</Project>
